---
- hosts: ubuntu
  become: yes
  roles:
    - role: ubuntu_base
  tags:
    - ubuntu_setup

- hosts: kubernetes_masters
  serial: 1
  become: yes
  roles:
    - role: kubernetes
      vars:
        k3s_token: "homelab01"
  tags:
    - kubernetes_setup
